### ISSUE TITLE
windowSize variable in hydropathy not substituted

### ISSUE THREAD

**Issue by tonigi** [andreasprlic/proteinfeatureview#2]
Occurs in the currently deployed version in RCSB.

![untitled1](https://cloud.githubusercontent.com/assets/2752011/7583544/a62d53f4-f896-11e4-8009-610f34c9e3e7.png)

**Comment by andreasprlic** [comment]
Thanks. I understand your report relates to the version on the RCSB PDB site? I am currently working on some major refactoring of the code base that is hosted here.

**Comment by andreasprlic** [comment]
fixed in latest RCSB build. Will be available in production as soon as the latest build gets deployed (should be later tonight or tomorrow morning)
